### ISSUE TITLE
[Question] Why when storing values in RequestCtx.Context it is only possible to use keys of type string?

### ISSUE THREAD

**Issue by nicolascb** [valyala/fasthttp#1014]
The signature to initialize a context allows me to use interface {} as keys:

[golang/src/context/context.go#L519](https://golang.org/src/context/context.go?s=16244:16304#L519)

```go
func WithValue(parent Context, key, val interface{}) Context
```

Why does the context in RequestCtx only accept strings as keys? Is there a specific reason for this?

[server.go#L2603](https://github.com/valyala/fasthttp/blob/master/server.go#L2603)
```go
// Value returns the value associated with this context for key, or nil
// if no value is associated with key. Successive calls to Value with
// the same key returns the same result.
//
// This method is present to make RequestCtx implement the context interface.
// This method is the same as calling ctx.UserValue(key)
func (ctx *RequestCtx) Value(key interface{}) interface{} {
	if keyString, ok := key.(string); ok {
		return ctx.UserValue(keyString)
	}
	return nil
}
```

I am writing some changes to make aws/x-ray compatible with fasthttp and I have some conflicts because of that.

**Comment by erikdubbelboer** [comment]
The reason is that fasthttp existed before context did and already had SetUserValue/UserValue functions which are very similar to the functionality of context. Support for context was added on top of this which is why it only supports strings as keys.

fasthttp is really made for use cases where you have thousands of requests per second that you have to answer really fast. For these cases you don't want to be using context as it causes a lot of garbage. So support for context was never really a priority for fastthtp.

**Comment by nicolascb** [comment]
Okay, got it.

I believe you have no problem modifying this behavior so that we can accept `interfaces` as keys, correct?

**Comment by erikdubbelboer** [comment]
A pull request is always welcome. I guess there should be a separate map for keys which aren't strings.

**Comment by logrusorgru** [comment]
Hm, interfaces just a bit slower https://gist.github.com/logrusorgru/ef64c38f0e67c7d7fc71015fab336737
But they solve collisions problem.

**Comment by erikdubbelboer** [comment]
I would be open for a pull request that uses `UserValue` for string keys and a `map[interface{}]interface{}` for all other keys. But I'm afraid I don't have time to build this myself right now.
