### ISSUE TITLE
Prefork method

### ISSUE THREAD

**Issue by jadbox** [valyala/fasthttp#104]
> Run a separate server instance per CPU core with GOMAXPROCS=1.

Question: Why does prefork tend to perform faster than one proc that's spawning a goroutine per request (eg FrameworkBenchmarks)? For Apache, spawning a thread per connection usually is faster, so it seems the same should apply to Go (especially since they are green threads).

**Comment by jadbox** [comment]
Also, why would prefork method work better than spawning a goroutine for each CPU to handle connections? It's effectively the same thing, but I assume instancing multiple versions of Go helps minimize GC pauses (or something).

**Comment by valyala** [comment]
> Why does prefork tend to perform faster than one proc that's spawning a goroutine per request?

Because distinct Go processes don't share state between each other in `prefork` mode. They work independently - the OS just spreads incoming connections among available independent processes via [SO_REUSEPORT](https://lwn.net/Articles/542629/). Shared state requires access serialization (aka synchronization), which hurts scalability for programs running on multiple CPU cores. See [Amdahl's law](https://en.wikipedia.org/wiki/Amdahl%27s_law) for details.

Even if your request handlers don't modify global shared resources such as maps, lists, etc., `fasthttp` server and `go` runtime may do this. For example, GC and timer subsystem modify global state.

> Why would prefork method work better than spawning a goroutine for each CPU to handle connections?

Actually each `fasthttp` process (which may be preforked) maintains a dynamic pool of worker goroutines for serving incoming requests. See [workerpool.go](https://github.com/valyala/fasthttp/blob/master/workerpool.go). Worker goroutines are created and destroyed on demand depending on the current number of established concurrent connections.

Initially `fasthttp` server was creating a goroutine per each incoming connection as [net/http.Server do](https://golang.org/src/net/http/server.go?s=63385:63431#L2097). Spawning a goroutine per connection is fast - multi-million goroutines per second may be created on an average hardware. I just optimized it further with [workerpool.go](https://github.com/valyala/fasthttp/blob/master/workerpool.go).

**Comment by manthedan** [comment]
I noticed that you recently removed the `prefork` method from your TechEmpower benchmark code. Do you no longer believe the `prefork` method to offer better performance?
