### ISSUE TITLE
idle connections closed by the server are not closed on fasthttp client 

### ISSUE THREAD

**Issue by dkuerner** [valyala/fasthttp#1063]
fasthttp does not seem to respect when the server signals that it wants to terminate an idle connection.

net/http client will immediately close the underlying tcp connection as soon as a FIN/ACK is received: 
![Bildschirmfoto 2021-08-02 um 13 32 01](https://user-images.githubusercontent.com/2082491/127856591-c2738edb-1cb5-4bdc-9047-30ce2684ce23.png)

fasthttp on the other hand will ACK the FIN/ACK sent by the server but the connection stays in the pool and will be attempted to be reused on the next request, resulting in a RST by the upstream server followed by opening a new connection:
![Bildschirmfoto 2021-08-02 um 13 31 41](https://user-images.githubusercontent.com/2082491/127856948-0396f5db-a8f2-4d0f-81ea-94f005973d32.png)

[tcpdumps.zip](https://github.com/valyala/fasthttp/files/6916927/tcpdumps.zip)

How to reproduce.
1. Setup a reverse proxy with fasthttp client
```go
package main

import (
	"github.com/valyala/fasthttp"
	"log"
)

var proxyClient = &fasthttp.HostClient{
	Addr: "localhost:8080",
	MaxConns: 1,
}

func ReverseProxyHandler(ctx *fasthttp.RequestCtx) {
	req := &ctx.Request
	resp := &ctx.Response
	if err := proxyClient.Do(req, resp); err != nil {
		ctx.Logger().Printf("error when proxying the request: %s", err)
	}
}

func main() {
	if err := fasthttp.ListenAndServe(":8091", ReverseProxyHandler); err != nil {
		log.Fatalf("Error in server: %s", err)
	}
}
```
2. Setup a reverse proxy with net/http client
```go
package main

import (
	"log"
	"net/http"
	"net/http/httputil"
	"net/url"
)

func reverseProxy(w http.ResponseWriter, req *http.Request) {

	upstream, err := url.ParseRequestURI("http://localhost:8080")
	if err != nil {
		log.Fatal("failed to parse upstream url")
	}
	proxy := httputil.NewSingleHostReverseProxy(upstream)
	proxy.Transport = &http.Transport{
		MaxConnsPerHost:        1,
	}
	proxy.ServeHTTP(w, req)

}

func main() {
	http.HandleFunc("/", reverseProxy)
	err := http.ListenAndServe(":8090", nil)
	if err != nil {
		log.Fatal("failed to start proxy")
	}
}
```
3. Setup a simple http server with idleConnectionTimeout set to 2 seconds
```go
package main

import (
	"io"
	"log"
	"net/http"
	"time"
)

func main() {
	h := func(w http.ResponseWriter, req *http.Request) {
		_, _ = io.WriteString(w, `{"message": "It is I"}`)
	}
	http.HandleFunc("/", h)
	srv := &http.Server{
		Addr: ":8080",
		IdleTimeout: 2 * time.Second,
	}
	log.Println(srv.ListenAndServe())
}
```
4. Make a curl request through each of the reverse proxy and after 2s idle timeout attempt another request

**Comment by moredure** [comment]
@dkuerner fasthttp doesn't create a goroutine per connection and not tracking connection state, that's is why you can see such a behaiviour: less goroutines to handle, better performance, lower number of context switches..., 
if you trapped in such a situation better to retry request or close connections immediately after response (Connection: close) to skip keeping connection alive.

**Comment by erikdubbelboer** [comment]
As you can see here: https://github.com/golang/go/blob/8a7ee4c51e992174d432ce0f40d9387a32d6ee4a/src/net/http/transport.go#L1747-L1748

`net/http` uses a separate goroutine for reading and writing to a connection. Because it constantly tries to read from a connection it will notice when that connection is closed.

`fasthttp` has no goroutines at all. The moment you want to send a request it gets an idle connection (or opens a new one) and writes the request to it. Only after that it will start reading from the connection. Because of this fasthttp will only notice a connection was closed by the other side when it tries to write to it.

As @moredure said, the best way to get the fasthttp client to close the connection is to send a `Connection: close` header: https://github.com/valyala/fasthttp/blob/9466cd7657c9b3e3ec7e2601114ffaaa739aeed4/client.go#L1449-L1450
