### ISSUE TITLE
clientDoDeadline's performance is not good

### ISSUE THREAD

**Issue by chhquan** [valyala/fasthttp#1072]
Hello,

I found that the clientDoDeadline's performance is not good, because it will raise a new routinue to send request and receive response. I think it is better to store context in Request likes http.Request. This can pass the context to underlying methods, such as HostClient.doNonNilReqResp, so doNonNilReqResp can use  context.Deadline to set connection deadline, and the client can implement Request Cancel。

**Comment by erikdubbelboer** [comment]
I agree the performance isn't great. `DoDeadline` is only really useful if you want to have a hard deadline for your request to return. But keep in mind that in de background the request will continue even if `DoDeadline` returned with a timeout.
For this reason I always recommend using a normal `Do` with `ReadTimeout` and `WriteTimeout` instead of `DoDeadline`.

I'm afraid we can't change the design now as it would break backwards compatibility.

What I would have liked is to use `time.AfterFunc` to kill the connection so we don't need a separate goroutine and the request won't continue in the background when DoDeadline returns. `context.Context` comes with it's own overhead so I would try to avoid those.

**Comment by chhquan** [comment]
@erikdubbelboer Thanks. It is good idea to use ReadTimeout/WriteTimeout, but sometimes different request has it is own deadline. 

I wonder  that how to use `time.AfterFunc`  to make it no need a seperate goroutine. What I think is to use `time.AfterFunc` to close the connection and then stop the goroutinue.

**Comment by erikdubbelboer** [comment]
`time.AfterFunc` can be used to close the connection which will the automatically stop the running request. But this change wouldn't be backwards compatible so it's hard to make.
