### ISSUE TITLE
FS handlers don't cooperate well with handleRequest on Windows 

### ISSUE THREAD

**Issue by Landryna** [valyala/fasthttp#1101]
'Root' field within fasthttp.FS requires existing filepath provided in Windows way ("C:\\Users\\...") however additonal data is added in unix way. Resolving in not finding any html files besides "/" path.
For example: My endpoint is set to /v1/login. I have my template files in dir "C:\\Users\\myfiles" (so i set fasthttp.FS{Root: C:\\Users\\myfiles}. When I make request to endpoint /v1/login -> additonal request path is added to filepath where my html templates should been. Resulting in final filepath: "C:\\Users\\myfiles/v1/login".  Resolving in not finding any template files.
Check implementation on fs.go line 796 version 1.29.0

**Comment by erikdubbelboer** [comment]
I don't think `FS` was really made with windows support in mind (without the linux subsystem). I see other places where this would go wrong as well. I don't have a windows machine to test this with either.
We would need to add [`filepath.FromSlash`](https://pkg.go.dev/path/filepath#FromSlash) in a bunch of places to convert `/` to `\`.

If you can find time for this and make a pull that would be awesome. Otherwise I'll try to make time somewhere in the near future.

**Comment by Landryna** [comment]
Sure, if I will get some spare time. Will do
