### ISSUE TITLE
my letsencrypt fasthttp is behind cloudflare...

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#1289]
with reference to this:
https://github.com/valyala/fasthttp/blob/master/examples/letsencrypt/letsencryptserver.go

how do i detect whether the incoming ip is cloudflare ip before all letsencrypt processing is done?
e.g. if remoteaddr / ip is detected from cloudflare, then i will not use letsencrypt autocert but my own private pem keys etc. and use cloudflare-ip header as the true ip address.

so how do i do that before all processing is done?

p.s. : basically if ip detected as proxied from cloudflare, i will use my own private key/pem and use cloudflare ip header 
cf-connecting-ip as the ip address.

possible to hv all these done before being tls terminated by letsencrypt?
for some websites not proxied by cloudflare, it will be terminated by letsencrypt.

thx in advance.

**Comment by erikdubbelboer** [comment]
Instead of `tls.NewListener` you'll have to use `ln.Accept` yourself to accept new connections. Then you can get the IP of the connection and use [`tls.Server`](https://pkg.go.dev/crypto/tls#Server) to create a secure connection (with the correct tls config based on the IP). And [`fasthttp.Server.ServeConn`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#Server.ServeConn) to serve requests on that connection.
