### ISSUE TITLE
Virtual Hosting

### ISSUE THREAD

**Issue by ohenepee** [valyala/fasthttp#130]
The vHost implementation confuses me... is it to allow multiple sites to be served on a single web server or just a way to get more information about the request from the client?

If its to serve multiple domains on a single server, could you please provide an example?

**Comment by valyala** [comment]
Browsers send site's domain name in `Host` header, so multiple domains (hosts) may be served by a single http server. Every http server which may access `Host` request header, may be used in virtual hosting. Since `fasthttp` may access `Host` header via [RequestCtx.Host()](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.Host), virtual hosting may be implemented on top of `fasthttp` by dispatching incoming requests based on the `Host` header. `fasthttp` provides out-of-the-box virtual hosting for static files - see [NewVHostPathRewriter](https://godoc.org/github.com/valyala/fasthttp#NewVHostPathRewriter).

See also [fileserver example](https://github.com/valyala/fasthttp/blob/master/examples/fileserver/fileserver.go), which provides virtual hosting support if `-vhost` command line flag is set. It serves files from `{dir}/{Host}/{Path}` for the url `http://{Host}/{Path}`.
