### ISSUE TITLE
can maxRedirectsCount in client.go be configured?

### ISSUE THREAD

**Issue by smallnest** [valyala/fasthttp#131]
Can maxRedirectsCount be exported so we can configure it as zero and then we can handle the redirect manually for clients?

**Comment by valyala** [comment]
@smallnest , `fasthttp` clients follow redirects only if methods returning response body as `[]byte` are called. Currently these are `Get*` and `Post*`. These methods must follow redirects, since they have no other possibilities to return redirect url.

`Do*` methods do not follow redirects, so the caller must handle them manually by inspecting the response after each `Do*` call.

I thinks there is no need in exporting maxRedirectsCount at the moment.

Updated documentation to make clear which client methods follow redirects and which don't.

**Comment by smallnest** [comment]
Got it, Thanks. 
I have implemented customized Do method.
