### ISSUE TITLE
for large scale high volume traffic site where fasthttp serves as a reverse proxy, what settings are ideal for HostClient?

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#1321]
for large scale high volume traffic site where fasthttp serves as a reverse proxy, what settings are ideal for HostClient?

```
        ProxyClient = &fasthttp.HostClient{

                IsTLS: true,
                TLSConfig: &tls.Config{
                        InsecureSkipVerify: true,
                },

                MaxConns: 1024000, // what's the recommended value?
                MaxIdleConnDuration: 30 * time.Second,
                ReadTimeout: 30 * time.Second,
                WriteTimeout: 30 * time.Second,
                // set other options here if required - most notably timeouts.
        }
```

**Comment by erikdubbelboer** [comment]
`1024000` for `MaxConns` should be more than enough. In your case I guess as long as it's a very high value it doesn't matter.

I would put `MaxIdleConnDuration` much higher. Since it's from server to server you will just want to have a lot of keep-alive connections open between them.

For a proxy I would set `DisableHeaderNamesNormalizing: true` and `DisablePathNormalizing: true` since you don't want fasthttp to modify the request.
