### ISSUE TITLE
Add transparent compression handling in the Response struct. 

### ISSUE THREAD

**Issue by szank** [valyala/fasthttp#14]
Hi, 
I was wondering if adding transparent compression handling in the code is feasible. 
Currently we check if the "Content-Encoding" header have a "gzip" value and decompress the data ourselves. 
I might do it myself if I have some free time on my hands, but I was wondering if this change would be even accepted

**Comment by valyala** [comment]
Currently the client doesn't set `Accept-Encoding` headers to `gzip` or `deflate`, so conforming server should never send compressed response with 'Content-Encoding' response header.

Transparent compression may be added to the client as opt-in setting in [Client](https://godoc.org/github.com/valyala/fasthttp#Client) and [HostClient](https://godoc.org/github.com/valyala/fasthttp#HostClient). `EnableCompression` is a good name for this setting. You may create pull request for this feature.

Enabling transparent compression in fasthttp client by default is no go, since default compression implementation in Go is slooow ;)

**Comment by szank** [comment]
My idea was to check for the 'Content-Encoding' header in the response, and decompress the body if the header was present. 
I didn't indent do modify the request sending path, only receiving. We could enable this behaviour by default, and disable it by setting 'AutoDecompress' to false in the client/response, where the value from the response would take precedence. 

Now, We could add a EnableCompression parameter also, to transparently compress the requests, but this is a story for another pull request.

**Comment by valyala** [comment]
Nice idea! I'll try implementing it on the next week.

**Comment by valyala** [comment]
@szank , I decided adding helper functions for body compression instead of transparent compression. This allows using response body compression only when needed.

See [Response.BodyGunzip](https://godoc.org/github.com/valyala/fasthttp#Response.BodyGunzip) and [Response.BodyInflate](https://godoc.org/github.com/valyala/fasthttp#Response.BodyInflate).

**Comment by valyala** [comment]
Added [CompressHandler](https://godoc.org/github.com/valyala/fasthttp#CompressHandler) for transparent response compression on server side.

**Comment by dibu28** [comment]
There is [github.com/klauspost/compress](http://github.com/klauspost/compress) a fully gzip compatible drop in replacement for go standard gzip/zip/zlib packages.
Claimed to be up to 3x faster for data compression.
Description and benchmarks by the author:
http://blog.klauspost.com/go-gzipdeflate-benchmarks/
http://blog.klauspost.com/gzip-performance-for-go-webservers/

[pgzip](https://github.com/klauspost/pgzip) Go parallel gzip compression/decompression. This is a fully gzip compatible drop in replacement for "compress/gzip". Faster for big files more than 1MB.

[cgzip](https://github.com/youtube/vitess/tree/master/go/cgzip) wraps zlib using cgo.

**Comment by sschepens** [comment]
What about transparent decompression of incoming requests to server?

**Comment by valyala** [comment]
Just added [Request.BodyGunzip](https://godoc.org/github.com/valyala/fasthttp#Request.BodyGunzip) helper.

Transparent compression / decompression won't be implemented in fasthttp, since this may be abused by specially crafted malicious requests / responses, which may eat a lot of CPU and memory resources.

**Comment by valyala** [comment]
I think this issue may be closed now. Feel free creating new issues for unresolved topics mentioned above.

**Comment by sschepens** [comment]
Great, thanks!
