### ISSUE TITLE
Please do not reset connection due the postBodySize exceeds the given limit

### ISSUE THREAD

**Issue by netroby** [valyala/fasthttp#156]
While set MaxBodySize, upload file bigger than the limit, the connection will be reset.
How to catch this error, then display a message to user, tell them do not post file larger than the limit. not just reset connections. thanks.

```
2016/08/10 16:32:36 error when serving connection "127.0.0.1:8080"<->"127.0.0.1:34904": body size exceeds the given limit
2016/08/10 16:32:36 error when serving connection "127.0.0.1:8080"<->"127.0.0.1:34906": body size exceeds the given limit
2016/08/10 16:32:51 error when serving connection "127.0.0.1:8080"<->"127.0.0.1:34910": body size exceeds the given limit
```

As a developer, I need a chance to code print some useful message tell user, what happened.

```
The max post file size is 20MB, please make sure check your file size. do not try to post file larger than 20MB. Thanks
```

**Comment by netroby** [comment]
https://github.com/kataras/iris/issues/353
The iris project using fasthttp.

**Comment by kataras** [comment]
Relative code: 

https://github.com/valyala/fasthttp/blob/45915c69f64b74b70461f427e2acd8a2947798b4/http.go#L1440
https://github.com/valyala/fasthttp/blob/45915c69f64b74b70461f427e2acd8a2947798b4/http.go#L894
https://github.com/valyala/fasthttp/blob/45915c69f64b74b70461f427e2acd8a2947798b4/server.go#L1496
https://github.com/valyala/fasthttp/blob/45915c69f64b74b70461f427e2acd8a2947798b4/workerpool.go#L215

A better action is to get the uploaded file size and get the developer/fasthttp user to check before logging this error and resetting the connection. Reference issue: https://github.com/valyala/fasthttp/issues/152

**Comment by kataras** [comment]
Relative code: 

https://github.com/valyala/fasthttp/blob/45915c69f64b74b70461f427e2acd8a2947798b4/http.go#L1440
https://github.com/valyala/fasthttp/blob/45915c69f64b74b70461f427e2acd8a2947798b4/http.go#L894
https://github.com/valyala/fasthttp/blob/45915c69f64b74b70461f427e2acd8a2947798b4/server.go#L1496
https://github.com/valyala/fasthttp/blob/45915c69f64b74b70461f427e2acd8a2947798b4/workerpool.go#L215

A better action is to get the uploaded file size in order to be able, the developer/fasthttp user, to check before logging this error and resetting the connection. Reference issue: https://github.com/valyala/fasthttp/issues/152

**Comment by kataras** [comment]
Relative code: 

https://github.com/valyala/fasthttp/blob/45915c69f64b74b70461f427e2acd8a2947798b4/http.go#L1440
https://github.com/valyala/fasthttp/blob/45915c69f64b74b70461f427e2acd8a2947798b4/http.go#L894
https://github.com/valyala/fasthttp/blob/45915c69f64b74b70461f427e2acd8a2947798b4/server.go#L1496
https://github.com/valyala/fasthttp/blob/45915c69f64b74b70461f427e2acd8a2947798b4/workerpool.go#L215

A better action is to get the uploaded file size in order to be able, the developer/fasthttp user, to check before logging this error and resetting the connection. Reference issue: https://github.com/valyala/fasthttp/issues/152 [maybe by headers?]

**Comment by netroby** [comment]
Any update now?

**Comment by netroby** [comment]
@valyala Would you please take a look?

**Comment by erikdubbelboer** [comment]
How would you expect fasthttp to report this to your program? Should it invoke the normal request handler but with an empty or partial body? How does `net/http` handle this?

**Comment by kirillDanshin** [comment]
@erikdubbelboer we could get us a special handler for that case (not a special handler type, probably, just a handler)

**Comment by erikdubbelboer** [comment]
So maybe we add an ErrorHandler that will be called when there's an error with as argument the request as far as it could be parsed and the error? Then programs can decide for themselves what they want to return.

**Comment by kirillDanshin** [comment]
@erikdubbelboer yeap
