### ISSUE TITLE
there does exist long latency before c.ConnTime()

### ISSUE THREAD

**Issue by cctse** [valyala/fasthttp#177]
There occasionally comes the problem that it will cost a long time before c.ConnTime() as showed in attached file.
![fast](https://cloud.githubusercontent.com/assets/3608665/18948112/59ff2f82-8668-11e6-9a39-a2a41543025e.png)

I have set the Server as follows, but it seems the ReadTimeout and WriteTimeout does not work
    s := fasthttp.Server{
        Name:"task",
        ReadBufferSize:4*1024,
        Handler:Handler,      // my handler 
        DisableKeepalive:true,      

```
    ReadTimeout: 3*time.Second,
    WriteTimeout: 5*time.Second,
} 
```

the main task in handler is check if there is a file upload,  if not then query data from mysql and return 

I have fmt.Println() the time which start the request on Client and the c.ConnTime() on Server to find the time is wasted before c.ConnTime()

**Comment by valyala** [comment]
> I have set the Server as follows, but it seems the ReadTimeout and WriteTimeout does not work

`ReadTimeout` makes sense only when reading request header and body from the network. `fasthttp` server reads the request header and body before passing it to user-defined `RequestHandler` (aka `Server.Handler`). `ReadTimeout: 3*time.Second` means that the server would close incoming connection if it couldn't receive the request during 3 seconds.

Similarly, `WriteTimeout` is used only when writing response header and body back to the client after the user-defined `RequestHandler` is finished. I.e. `WriteTimeout: 5*time.Second` means that the server would close the connection if it couldn't send the response during 5 seconds.

As you can see, both settings cannot limit execution duration for user-defined `RequestHandler`. There is an [TimeoutHandler](https://godoc.org/github.com/valyala/fasthttp#TimeoutHandler), which may be used for limiting the maximum `RequestHandler` duration.

As for the [RequestCtx.ConnTime](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.ConnTime), it returns the time the connection is initially established. [hey](https://github.com/rakyll/hey) by default uses [http keep-alive](https://en.wikipedia.org/wiki/HTTP_persistent_connection) connections, i.e. it sends multiple requests over a single connection. So `time.Since(ctx.ConnTime())` would return increasing duration values for long-lived keep-alive connections. Try using [RequestCtx.Time](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.Time) instead for measuring `RequestHandler` execution duration.

As for 13-second responses, I think they may be related either to db or TCP connections' establishing. Try passing `-more` to `hey` for additional info.

**Comment by kataras** [comment]
@valyala I see from your answer that it's not a bug but it's labeled as bug, can you explain me the bug in order to try to fix?

**Comment by valyala** [comment]
@kataras, I just labeled the issue as a potential bug. I need more info from the reporter, @cctse, to determine whether this is a bug or not a bug.

**Comment by kataras** [comment]
ah okey, then we just wait then, thanks :)

**Comment by kataras** [comment]
ah okey, we just wait then, thanks :)

**Comment by cctse** [comment]
here is a more simple code 
`
package main

import (
	fst "github.com/valyala/fasthttp"
	"fmt"
	"encoding/json"
	"time"
)

func main()  {

	fmt.Println("serv on: 8083")
	fst.ListenAndServe(":8083", func(c *fst.RequestCtx) {
		body,_ := json.Marshal(struct {
			Hello string `json:"hello"`
		}{
			"fasthttp",
		})

		c.Write(body)

		if time.Since(c.ConnTime())>time.Second{
			// there can't catch anything
			fmt.Println(c.ConnTime(), c.Time(), c.Time().Sub(c.ConnTime()))
		}
	})
}
`
I used ab to test, it also comes the problem
![838e862a-5695-42e3-ae8e-590f69d4d7b9](https://cloud.githubusercontent.com/assets/3608665/19585494/992145a6-977f-11e6-9e80-5af4afaba676.png)

does ab also use  http keep-alive connections too? it seems not from the ab test report
