### ISSUE TITLE
HEAD request returning 200 OK with no body will hang indefinitely

### ISSUE THREAD

**Issue by krzysztofsmigiel** [valyala/fasthttp#1824]
Hi!
While working with Fiber and it's Proxy middleware https://github.com/gofiber/fiber/tree/main/middleware/proxy I've encountered weird bug.
When I am heading to `HEAD http://myproxy`, server returns:
```
HTTP/1.1 200 OK
X-elastic-product: Elasticsearch
content-type: application/json
Transfer-Encoding: chunked
```

When I am trying to do the same with `client.Do()` it hangs forever here

```
/go/pkg/mod/github.com/valyala/fasthttp@v1.55.0/header.go

func (h *ResponseHeader) tryRead(r *bufio.Reader, n int) error {
	h.resetSkipNormalize()
	b, err := r.Peek(n) <<< Hangs here forever.
	if len(b) == 0 {
		// Return ErrTimeout on any timeout.
		if x, ok := err.(interface{ Timeout() bool }); ok && x.Timeout() {
[...]
```

I am not that experienced with fasthttp, but it _might_ be related with `Transfer-Encoding: chunked` returned by the server for this HEAD request.

**Comment by newacorn** [comment]
Head requet trigger Skip Body pattern. If your heading server send chunked body(not follow the HTTP protocol, not empty body) as head response. fasthttp client must hang forever.
If you want solve this problem，simple do this:
https://github.com/valyala/fasthttp/blob/9fe0bc2e6fafad8a28d1cb64cc07c7953f32abd7/http.go#L1439
```go
	if !resp.mustSkipBody() {
		err = resp.ReadBody(r, maxBodySize)
		if err != nil {
			if isConnectionReset(err) {
				return nil
			}
			return err
		}
		//}

		if resp.Header.ContentLength() == -1 && !resp.StreamBody {
			err = resp.Header.ReadTrailer(r)
			if err != nil && err != io.EOF {
				if isConnectionReset(err) {
					return nil
				}
				return err
			}
		}
	}
```
But now, if your sever send head or other without  body chunked response you never read trialer header. but I think it ok. 

A better approach is to have the ReadTrailer method perform the check, and if the chunked ending is not correct, it should immediately return an error rather than waiting indefinitely for the server to send a valid chunked ending byte stream.

Currently, fasthttp mixes the handling of user-defined skipBody and skipBody required by the HTTP protocol, which can lead to other issues. A comprehensive fix is needed. However, the code above can temporarily solve your problem effectively.

**Comment by newacorn** [comment]
## Test Replay:
```go
func TestClientSkipRespBodyDontReadTrailer(t *testing.T) {
	server := Server{Handler: func(ctx *RequestCtx) {
		_, err := ctx.WriteString(randomstring.HumanFriendlyString(1024))
		ctx.Response.SetBodyStream(strings.NewReader(randomstring.HumanFriendlyString(1024)), -1)
		assert.NoErr(t, err)
	}}
	req := AcquireRequest()
	defer func() {
		ReleaseRequest(req)
	}()
	req.SetRequestURI("http://127.0.0.1:7070")
	resp := AcquireResponse()
	resp.SkipBody = true
	//
	pcs := fasthttputil.NewPipeConns()
	cliCon, serCon := pcs.Conn1(), pcs.Conn2()
	err := cliCon.SetReadDeadline(time.Now().Add(time.Second*5))
	assert.NoErr(t, err)
	go func() {
		_, err := req.WriteTo(cliCon)
		assert.NoErr(t, err)
		err = resp.Read(bufio.NewReader(cliCon))
		assert.NoErr(t, err)
		err = cliCon.Close()
		assert.NoErr(t, err)
	}()
	//
	err = server.serveConn(serCon)
	if err != nil && !strings.Contains(err.Error(), "closed") {
		t.Fatal(err)
	}
}
```
## Result
```
=== RUN   TestClientSkipRespBodyDontReadTrailer
    http_test.go:3201: 
          Test Name:  TestClientSkipRespBodyDontReadTrailer
          Error Pos:  /Users/acorn/workspace/programming/golang/wx/fasthttp/http_test.go:3201
          Error Msg:  Received unexpected error:
                      error when reading response headers: timeout. Buffer size=1036, contents: "400\r\nidobatobiratusakupibanudabumosenabidesoluponepuvogiveooparumalotimobegiruvadiouvetumagoyadivukavoaeooeuioouaoeiouaaieeouiiaeeioeeuaeeoaioauoieoiaaeoaeouiaaoiauuoieooeeooiaoiaeiieoaeeaaiieuaoiuuoa"..."oiuoiiaeuaooiauoaeiaeeouiieuaaeoiaoeiaoeuooaiuueaieaiuaooiaeiaeeaoueiauiiueoieeoaeiioaeoiaoeuuoiauooaeuuiiaaeeaieeouieeuoiaeeaueaoeuiaoeiiouieeiouiieaooaiiaeooeaoeiaaoiiueiaeiueeiuaaiioaueeioee\r\n0\r\n\r\n"
--- FAIL: TestClientSkipRespBodyDontReadTrailer (1.00s)
```
## After FIx
```
=== RUN   TestClientSkipRespBodyDontReadTrailer
--- PASS: TestClientSkipRespBodyDontReadTrailer (0.00s)
PASS
```
But this is a tmp fix.

**Comment by erikdubbelboer** [comment]
What is happening is that the client doesn't expect a response body for the `HEAD` request as that's not possible according to the HTTP spec. So it either fails to read the trailers (which is a bug in fasthttp, since you can't have trailers without a body). Or if there is a timeout set, it will timeout and retry the request, it then tries to read a proper response from the connection while the body of the HEAD response is still on it. So it fails to parse the body of the HEAD response as response trailers and hangs on that. If you set a ReadTimeout it will just fail with a timeout.

https://github.com/valyala/fasthttp/pull/1825 here are some fixes for issues I found while investigating this. But it doesn't fix your main issue of a HEAD having a response. This is just invalid HTTP and we won't support this. `net/http` also prints `Unsolicited response received on idle HTTP channel starting with "24\r\nThis is the data in the first chunk \r\n1B\r\nand this is the second one \r\n0\r\n\r\n"` when you try this.

**Comment by krzysztofsmigiel** [comment]
Thanks you guys for thoughtful research! Now I understand problem more. There is one caveat: my code hands even _before_ reaching `if !resp.mustSkipBody() {` on line 1437. It hangs before:
```
func (resp *Response) ReadLimitBody(r *bufio.Reader, maxBodySize int) error {
	resp.resetSkipHeader()
	err := resp.Header.Read(r) <<<<<<<<<<
	if err != nil {
		return err
	}
```
So even before considering `SkipBody` and reading trailers.
This malfunctioned response is sent by donwstream server which I have no control, since I am using Fiber as reverse proxy. As I understand, sending HEAD with `Transfer-Encoding: chunked` with no valid byte termination `0\r\n\r\n` results in error in fasthttp?

**Comment by krzysztofsmigiel** [comment]
> By the way, if this leftover data is crafted appropriately, it could cause the parsing to hang indefinitely when treated as response headers, rather than reporting a parsing error. So, if you find that some code hangs while parsing response/request headers, it might not be an issue with the headers of the current response/request but rather leftover data from the previous one, especially with long connections. Therefore, you should debug to see exactly what data is causing the header parsing to hang.

After some debugging it seems that `resp.Header.Read(r)` tries to read from `r` buffer, **which is empty**. When passing hand-crafted empty buffer it also hangs in this method. For clarification, downstream returns HEAD response without body, just weird `Transfer-Encoding: chunked` header.

**Comment by krzysztofsmigiel** [comment]
To summarise:
# When HEAD request is sent with `Transfer-Encoding: chunked` without proper byte termination it will hang forever.
# There is no workaround yet, #1825 will fix _some_ problems but main case from this issue is not considered.

Debugging shows that it hangs while reading Headers (before reading Body) from connection. This is all I was able to debug with my knowledge.

**Comment by erikdubbelboer** [comment]
My advise would be to, either set a read timeout so bad requests like this won't hang, or to make sure the client speaks proper HTTP.
