### ISSUE TITLE
Method-preserving doRequestFollowRedirects in client.go

### ISSUE THREAD

**Issue by prepaser** [valyala/fasthttp#1916]
Redirecting in HTTP/1.1 typically preserves methods, but conventionally changes the POST method to GET for 301/302 responses. Browsers such as Chrome also follow this behavior. However, doRequestFollowRedirects in client.go always preserves methods, sometimes causing problems.

I've been having this problem. Can you add comment or support this? I think this should also be implemented in the redirect function.

rfc9110:

> Note: For historical reasons, a user agent MAY change the request method from POST to GET for the subsequent request. If this behavior is undesired, the 307/308 status code can be used instead.

**Comment by didyoumean** [comment]
Hey @prepaser @erikdubbelboer this is actually a breaking change.

Is there way to specify the desired behaviour of the library? We used fasthttp specifically because it was preserving the HTTP method. 

As a client app which makes request to external web server we have no control over the server behaviour. If it expects a redirect to be made with POST we're screwed now. Ideally this should be configurable behaviour of the library.

**Comment by erikdubbelboer** [comment]
I'm open to a pull request to add a setting to configure this.
