### ISSUE TITLE
Session support for fasthttp

### ISSUE THREAD

**Issue by EtienneBruines** [valyala/fasthttp#194]
# The case-scenario
I want users to be able to log-in. 

# The "solution"
Usually by means of sessions, i.e. [Gorilla Sessions](https://github.com/gorilla/sessions). 

# The "problem"
Fasthttp is [incompatible](https://github.com/gorilla/sessions/issues/85) with gorilla sessions. 

I have also seen [this implementation](https://github.com/fasthttp-contrib/sessions), but I'm hesitant to use it because the maintainer is currently receiving lots of criticism. 

---------
# My question
Is there any other way to achieve the "user is logged in"-feature within fasthttp? Or is making gorilla sessions compatible with fasthttp the only solution? 

Thanks.

**Comment by EtienneBruines** [comment]
Okay, apparently github issues aren't always up-to-date. 

Someone already created a compatible version of Gorilla Sessions, here: https://github.com/clevergo/sessions

Apologies for the inconvenience.

**Comment by kataras** [comment]
What about https://github.com/kataras/go-sessions ? Its compatible both fasthttp and net/http :)

**Comment by kataras** [comment]
@EtienneBruines I think you speak for myself,  you shouldn't because it supposed that you know me for 2+ months and you know that I sit all nights to write the framework that they are fighting through via , but everyone can accept propaganda, even you, right? Anyway, I don't like to answer to accusations but I did it here: https://github.com/kataras/iris/issues/504

**Comment by kataras** [comment]
@EtienneBruines I think you speak for myself,  you shouldn't because it supposed that you know me for 2+ months and you know that I sit all nights to write the framework. That they are fighting iris through me and its not the first time, but everyone can accept propaganda, even you, right? Anyway, I don't like to answer to accusations but I did it here: https://github.com/kataras/iris/issues/504

**Comment by kataras** [comment]
@EtienneBruines I think you speak for myself, you shouldn't because it supposed that you know me for 2+ months and you know that I sit all nights to write the framework. That they are fighting iris through me and its not the first time, but everyone can accept propaganda, even you, right? Anyway, I don't like to answer to accusations but I did it here: github.com/kataras/iris/issues/504 .

@valyala sorry for posting here but I couldn't stop writing this comment, he dissapointed me a lot. I will not write anything else about the accusation here, we are not in blog neither reddit*

**Comment by headwindfly** [comment]
@EtienneBruines I recommend to use this -- https://github.com/go-gem/sessions, it's API is similar with Gorilla Sessions, the clevergo's sessions is no longer maintained.
