### ISSUE TITLE
Questions of TimeoutHandler

### ISSUE THREAD

**Issue by headwindfly** [valyala/fasthttp#200]
The code can always be processed , even request timeout.
Is it possible to stop it when request timeout?

Code:
```
func main() {
	fasthttp.ListenAndServe(":8080", fasthttp.TimeoutHandler(func(ctx *fasthttp.RequestCtx) {
		log.Println("begin")
		time.Sleep(time.Second * 5)
		// How to stop when timeout?
		log.Println("end")
	}, time.Second * 2, "timeout"))
}
```

Output:
```
2016/11/15 18:06:10 begin
2016/11/15 18:06:15 end
```

**Comment by valyala** [comment]
@headwindfly , `fasthttp` doesn't provide any mechanisms which can stop execution of user-defined [RequestHandler](https://godoc.org/github.com/valyala/fasthttp#RequestHandler). [TimeoutHandler](https://godoc.org/github.com/valyala/fasthttp#TimeoutHandler) doesn't stop the `RequestHandler` - it only returns `request timed out` response to the client on timeout.

Your handlers must be aware of the timeout in order to properly stop execution after the timeout. This may be achieved either manually or by wiring [context.Context](https://golang.org/pkg/context/) into all the functions involved in request processing. Read [this article](https://blog.golang.org/context) for more info.

The `Context` may be stored in `RequestCtx` via [RequestCtx.SetUserValue](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.SetUserValue).

**Comment by headwindfly** [comment]
Thanks.

**Comment by tsingson** [comment]
helpful discussion

**Comment by fairyhunter13** [comment]
> @headwindfly , `fasthttp` doesn't provide any mechanisms which can stop execution of user-defined [RequestHandler](https://godoc.org/github.com/valyala/fasthttp#RequestHandler). [TimeoutHandler](https://godoc.org/github.com/valyala/fasthttp#TimeoutHandler) doesn't stop the `RequestHandler` - it only returns `request timed out` response to the client on timeout.
> 
> Your handlers must be aware of the timeout in order to properly stop execution after the timeout. This may be achieved either manually or by wiring [context.Context](https://golang.org/pkg/context/) into all the functions involved in request processing. Read [this article](https://blog.golang.org/context) for more info.
> 
> The `Context` may be stored in `RequestCtx` via [RequestCtx.SetUserValue](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.SetUserValue).

@razonyang Does it mean that no further write to the writer (ctx) when the request is a timeout?

**Comment by razonyang** [comment]
@fairyhunter13 As my understanding, the request was always processed anyway.
If you want  to stop handling request when timeout reached, you could follow the suggestions that valyala mentioned.

**Comment by erikdubbelboer** [comment]
Writing to the `ctx` after the timeout won't do anything and will be discarded.

**Comment by dimovnike** [comment]
It would have been better and more intuitive if the context was cancelled on the timeout. Would you accept a PR with this change?

**Comment by erikdubbelboer** [comment]
I'm afraid fasthttp is not made to be intuitive, and definitely not with contexts in mind. Best would have been if we never implemented the context methods such as `Done()`, but we can't remove these anymore now. Having `Done()` be closed on a timeout would mean an allocation of a new channel for every timeout. This is something that is not acceptable I'm afraid.
