### ISSUE TITLE
Content-Type Transparency

### ISSUE THREAD

**Issue by aaronshurley** [valyala/fasthttp#214]
Currently, if no `Content-Type` is present in the response header, fasthttp sets a default `Content-Type` to `text/plain; charset=utf-8`:  https://github.com/valyala/fasthttp/blob/ef299a95e2a898859c8652374b33cc7553b1532e/header.go#L270

We would like to provide a transparent proxy and do not want to add (or default) the `Content-Type`, if it is not present. Is there any way around this or would you be interested in a PR that adjusts this behavior?

**Comment by erikdubbelboer** [comment]
I would say removing the default content type completely would be the best. If people don't set a content type we shouldn't set it for them.
But for backwards compatibility we can't do this anymore.

I think the second best alternative would be to be able to set a `DefaultContentType` in the `Server` struct.

**Comment by davidbyttow** [comment]
I took a stab at this. I didn't opt for `DefaultContentType` in `Server` because even setting it to empty string would end up being overridden in header.go when the ContentType() is retrieved. This should be backward compatible at the server level, as it will automatically attach the defaultContentType if not configured explicitly. https://github.com/valyala/fasthttp/pull/407
