### ISSUE TITLE
URI().Path bytes to string

### ISSUE THREAD

**Issue by iowelinux** [valyala/fasthttp#22]
Hi,

It's told to avoid conversion between []byte and string 'cause Fasthttp API provides functions for both.
However I've looked through the code and haven't found a function that would return a string for Path.
There is URI().String() but I don't see the same for URI().Path()

It seems the only way to sort this out is to convert from bytes to string but it's not recommended by you :)
Is there any other way to get Path as a string?

Thanks.

**Comment by valyala** [comment]
Hi @iowelinux ,

fasthttp API doesn't provide `Path().String()` because it cannot be implemented reliably without memory allocation. There is [a hack](http://stackoverflow.com/a/27614755/274937), which allows converting `[]byte` to `string` without memory allocation, but it may break in new go versions, so fasthttp API doesn't use it. So just use `string(URI().Path())` if you cannot use `[]byte` result. This will allocate memory for `string` and copy `[]byte` contents into `string`. Or use the aforementioned hack on your own risk :)

**Comment by valyala** [comment]
@iowelinux , see the update for `string` conversion exceptions.
