### ISSUE TITLE
Timeout when Header's Content-Length not equal real length of the Body

### ISSUE THREAD

**Issue by alehano** [valyala/fasthttp#289]
If request Content-Length not equal real body size, it cause request timeout. Is there a way to ignore Header's Content-Length manually? Please, need help.

**Comment by erikdubbelboer** [comment]
I'm afraid there is no way to tell fasthttp to allow invalid requests.

If you want it to ignore the Content-Length header then when will it know it is done reading the body? The only option not to send a Content-Length header is to use a chunked Transfer-Encoding.

**Comment by alehano** [comment]
Can I patch the fasthttp source code to ignore Content-Length in the header?
I didn't find the right place.

**Comment by erikdubbelboer** [comment]
What do you expect it to do with it ignores the Content-Length header? Can it just read 1 byte and return that byte as body? Or 1000 bytes? But then what if the body is smaller than that, should it timeout? What if the body is bigger, should it see the rest of the body as a new request? There is a reason the Content-Length header exists.

**Comment by alehano** [comment]
You know, when I test POST requests and if I remove Content-Length from header, all works. But if there is a Content-Length with wrong size, it doesnt work. So I want to remove Content-Length from incoming requests to let handle them

**Comment by erikdubbelboer** [comment]
I'm guessing when you aren't sending Content-Length you are using Transfer-Encoding instead? Because if you don't set either fasthttp will not read any body at all.

See:
https://github.com/valyala/fasthttp/blob/52a0993b96f032dea57fa93081d7c0a1aa906430/header.go#L1731-L1733
and
https://github.com/valyala/fasthttp/blob/8948e047bf8d450654c649d578f7660fc073d8f6/http.go#L915-L954
And: https://github.com/valyala/fasthttp/blob/8948e047bf8d450654c649d578f7660fc073d8f6/http.go#L1570-L1582
