### ISSUE TITLE
fasthttp.SaveMultipartFile rename /tmp/multipart-109150364 : invalid cross-device link

### ISSUE THREAD

**Issue by longkeyy** [valyala/fasthttp#391]
curl -F "csv=@test" http://localhost:8080/upload

when test is big then 8G

**Comment by erikdubbelboer** [comment]
`mime/multipart` will use `ioutil.TempFile()` which uses [`os.TempDir()`](https://golang.org/pkg/os/#TempDir) to find a directory to place the temporary file in. `fasthttp.SaveMultipartFile()` then tries to rename this file instead of making a copy. On systems where the temporary directory is on a different disk than the disk you want to move the file to it will give this error.
