### ISSUE TITLE
How does Response.Write make sure that client can receive reponse-bytes immediately without Flush() opt ?

### ISSUE THREAD

**Issue by stormgbs** [valyala/fasthttp#40]
As described in the title. How does Response.Write make sure that client can receive reponse-bytes immediately without Flush() opt ?

**Comment by valyala** [comment]
There were two options for sending responses with fasthttp until today:

1. Via [fasthttp.Server](https://godoc.org/github.com/valyala/fasthttp#Server). The server automatically sends http response after user's code returns from the outer [RequestHandler](https://godoc.org/github.com/valyala/fasthttp#RequestHandler) . See Server.serveConn implementation for details.

2. Via [Response.Write](https://godoc.org/github.com/valyala/fasthttp#Response.Write) call. In this case the caller *must* call bufio.Writer.Flush in order to make sure the response is sent to the client.

After [the commit)[https://github.com/valyala/fasthttp/commit/f8c0d95e57fe628cb7c005ec3afbccd4cc607db3] yet another approach has been appeared for sending responses - using [Response.WriteTo](https://godoc.org/github.com/valyala/fasthttp#Response.WriteTo).

**Comment by stormgbs** [comment]
Thank @valyala , fasthttp is owesome:) .  I am writeing a http router(http reverse proxy) based on fasthttp, I modified some fasthttp code, so that  I can copy response bytes from lower conn(proxy<-->backend server) to upper-conn(client <--> proxy) directly.
