### ISSUE TITLE
func (s *Server) Shutdown() leads to app termination

### ISSUE THREAD

**Issue by brotherdetjr** [valyala/fasthttp#406]
Hi all,
I've got the following shutdown handler:
```
var shutdownCh = make(chan os.Signal, 1)
signal.Notify(shutdownCh, syscall.SIGTERM)
signal.Notify(shutdownCh, syscall.SIGINT)
go func() {
	for range shutdownCh {
		logger.Info().Msg("Shutting down")
		httpServer.Shutdown()
		logger.Info().Msg("After shutting down")
	}
}()
```
(`httpServer` is of type `*fasthttp.Server`, obviously) 
When I send `SIGINT` to the application I expect to see both log messages. However, I see only "Shutting down". I tried to debug and spot, where the application terminates. I started drilling from `server.go` `func (s *Server) Shutdown()`. Somewhere in `s.ln.Close()` bad things happened. I drilled deeper into `netpoll.go` (`netpollgoready` call from `func poll_runtime_pollUnblock(pd *pollDesc)`), and the application terminated on that call, no further "step into" debug step was possible. No panic messages, no errors - just "Debugger finished with exit code 0".

Is this OK or not? How to implement a graceful shutdown for `fasthttp.Server` when handling `SIGINT`/`SIGTERM`? What am I doing wrong?

OS: Elementary 0.4.1 Loki (Ubuntu based)
go version go1.10.3 linux/amd64

Regards,
Denis

**Comment by erikdubbelboer** [comment]
Your problem is that calling `httpServer.Shutdown()` makes `httpServer.Serve()` return which I guess makes your main function return and your program end.
What you normally do is call `httpServer.Serve()` in a goroutine and call `httpServer.Shutdown()` from the main function as it blocks until the server is completely shut down.
Just make sure you do `<-shutdownCh` instead of your range loop otherwise your main function never stops.
