### ISSUE TITLE
Missing important getter methods of *Args

### ISSUE THREAD

**Issue by metakeule** [valyala/fasthttp#43]
the most obvious methods of `*Args` are missing:

```go
func (*Args) Get(key string) string {
}

func (*Args) GetBytes(key string) []byte {
}
```

**Comment by valyala** [comment]
Unfortunately due to historical reasons these methods have non-obvious names - see [Peek](https://godoc.org/github.com/valyala/fasthttp#Args.Peek) and [PeekBytes](https://godoc.org/github.com/valyala/fasthttp#Args.PeekBytes).

These methods are named `Peek` instead of `Get`, because they return `[]byte` slices, which belong to `Args` object.

**Comment by metakeule** [comment]
Ok, but why not offering a method Get that returns a string? Seems one of the most important use cases.

**Comment by valyala** [comment]
Because returning `string` requires memory allocation and copy, which may slow down fasthttp. Use `string(args.Peek("foo"))` if you prefer working with strings and don't care about memory allocations.
