### ISSUE TITLE
Investing time and effort into fasthttp question.

### ISSUE THREAD

**Issue by unisqu** [valyala/fasthttp#433]
Sorry to ask here, I'm about to invest a lot of time and effort in this. Need clarify.

1. if I put net/http in front of fasthttp, will that resolve all issues that fasthttp have? trying to use fasthttp as reverse proxy. i understand net/http can be 10x slower.
2. I don't understand when I should not be using fasthttp other than http/2 for now. 
It's not browser compatible across all client browsers?
3. under what circumstances should i NOT be using fasthttp? i read somewhere regarding no http header... is that correct? hope clarification of these 3 questions can be written on mainpage of github. 

p.s. : so far i've written code as api and satisfied with using fasthttp as api only. I'll do file upload etc but the net/http scare online is very unnerving without the latest 3 explanations above. Thanks in advance.

**Comment by erikdubbelboer** [comment]
1. I'm not sure which issues you are talking about? But how do you envision putting `net/http` in front of `fasthttp`? That concept doesn't make much sense to me?
2. `fasthttp` is compatible with all browsers and clients that we know of. If anyone can show us a special case which isn't handled we'll gladly fix it.
3. I'm not sure what you mean with `"regarding no http header"`? In theory `fasthttp` is fine to use in all circumstances. Of course it isn't as well testing as `net/http` because it doesn't have as many users but `fasthttp` is being used for real production applications by many companies.

**Comment by unisqu** [comment]
1. using as reverse proxy
2. ok
3. seemed ok to me then. so why isnt everyone switching to fasthttp?

**Comment by kirillDanshin** [comment]
@unisqu 
1. I'd suggest you to use fasthttp as reverse proxy too, when you'll get some time for it
2. _
3. I think developers got used to `net/http` and its ecosystem. e.g. we have many `net/http`-based frameworks and libraries, but not so much `fasthttp`-based ones

**Comment by unisqu** [comment]
thanks. switching from iris now.
