### ISSUE TITLE
potential leak

### ISSUE THREAD

**Issue by amezghal** [valyala/fasthttp#448]
https://github.com/valyala/fasthttp/blob/1b3ac0ccc9a9a57dd7dd0876a12a0d8e27b06582/client.go#L969

the select case will be executed only once, and if the timeout channel was notified before the client.do finishes,
then the code 

```
if resp != nil {
			respCopy.copyToSkipBody(resp)
			swapResponseBody(resp, respCopy)
		}
		swapRequestBody(reqCopy, req)
		ReleaseResponse(respCopy)
		ReleaseRequest(reqCopy)
		errorChPool.Put(chv)
```

Will never be executed, and you will never release the request/response..

**Comment by erikdubbelboer** [comment]
Yes in case of a timeout there is no proper cleanup. Of course real memory leaks in Go are very very rate so in this case the Garbage Collector will just take care of the cleanup. This does mean that in case of a timeout we'll have some garbage on the heap, something that fasthttp tries to avoid. The problem here is that proper cleanup requires some more complicated code as it needs to first wait for the request to finish before it can be cleaned up. Pull requests to add this are always welcome!

**Comment by amezghal** [comment]
check my pull request
