### ISSUE TITLE
byte range issue

### ISSUE THREAD

**Issue by iowelinux** [valyala/fasthttp#47]
Hi,

Seems like an issue with byte range requests.

E.g.
File size: 210720491 bytes

When I send a request with the header "Range: bytes=95644624-" fasthttp handles it correctly.
However if we'll modify the header to "Range: bytes=95644624-210720491" (from 95644624 to the last byte of the file) it drops to 416 http error because it can't handle the byte range.

`cannot parse byte range "bytes=97851544-210720491" for path="/some_file.dat": invalid byte range`

For instance I've just checked Nginx and it handles the same query correctly.

**Comment by valyala** [comment]
Thanks for the bug report, @iowelinux .

According to [byte range RFC](https://tools.ietf.org/html/rfc7233#section-2.1):

> The last-byte-pos value gives the byte-offset of the last byte in the range; that is, the byte positions specified are inclusive.  Byte offsets start at zero.

This means that the last byte of your file must be `210720490`, not `210720491`. It looks like nginx has a workaround for this one-off error, since the error is quite widespread. I'm investigating this further and will add the corresponding workaround if required.

**Comment by valyala** [comment]
Nginx implements new byte range RFC, which allows out-of-range end position. See [the corresponding commit](https://github.com/nginx/nginx/commit/451df22b3f07d4e11ea8b32cc932630ae383d280) and [the corresponding RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35).

I'll implement the same in fasthttp

**Comment by valyala** [comment]
Fixed.
