### ISSUE TITLE
Disable/Configure the ignoreBody behavior

### ISSUE THREAD

**Issue by danielfireman** [valyala/fasthttp#479]
Good morning!

I am trying to use fasthttp as reverse and one of the proxied services I am testing right now is Elasticsearch, which does have the notion of [search queries with request bodies](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html) (those are GET requests)

After some time debugging, I finally got everything up and ran into the following problem:

> non-zero body for non-POST request. body="{\"query\":{\"term\":{\"key\":\"user6471881514242715297\"}}}

Is that possible to somehow add an option to disable this check? I am keen to go ahead and send a PR, but it would be great to have some clarifications beforehand. What is the recommended way to go? A new option in the client, maybe?

**Comment by erikdubbelboer** [comment]
I have tried changing this behavior in fasthttp the last couple of days but I haven't been successful yet. The problem is that a lot of code in fasthttp depends on certain assumptions about the `contentLength` variable. I'm afraid that I don't have for the next couple of weeks as I'm moving cross country. Pull requests are always welcome, otherwise I'll have a look at this next year probably.

**Comment by danielfireman** [comment]
Sorry for the delay on responding.

I didn't check that carefully the dependency on `contentLenght`, so I wasn't aware that was that hard. Thanks for the clarifications!

I am closing the PR since it was very specific to my experiment (not even look like usual REST). Considering the risk, I believe it does not worth the trouble.
