### ISSUE TITLE
Cookie peeking is confusing

### ISSUE THREAD

**Issue by dgrr** [valyala/fasthttp#508]
Hello,

Diving into fasthttp source code I found some confusing things related with Cookie methods.
In the RequestHeader structure we have the [Cookie method](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.Cookie) which receives a string and returns a byte slice. Also we have [CookieBytes method](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.Cookie) which does the same but receiving a byte slice. But, in other way we found that ResponseHeader has a method called [Cookie](https://godoc.org/github.com/valyala/fasthttp#ResponseHeader.Cookie) which receives a Cookie structure. And, in other way we found that ResponseHeader has [PeekCookie method](https://godoc.org/github.com/valyala/fasthttp#ResponseHeader.PeekCookie) which does the same than [RequestHeader.Cookie](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.Cookie).

This lack of uniformity makes the API a bit confusing for new users. I know that a change in the API could affect backwards compatibility.

Do you think this is an issue?

**Comment by erikdubbelboer** [comment]
I agree the methods are confusing. I guess the way it was designed like this is because request cookies are always only have `key=value` while response cookies can have all kinds of attributes so they need a struct with methods to access them.

That there are both string and byte methods is quite usual for fasthttp as it depends on what kind of data you have that using a string or slice might be faster and use one less allocation.

Changing the methods is not an option unless we do something like fastthtp2. Adding new methods that are the same for request and response and deprecating the old methods is possible but would for now only add even more methods which I think would end up making it even more confusing.

**Comment by caibirdme** [comment]
@dgrr I think these APIs might be OK, xxxBytes just means that the method needs a slice of bytes as its **parameter**. Passing a []byte could avoid a copy operation compared to passing a string.
