### ISSUE TITLE
RequestCtx.SendFile doesn't consider Range request header

### ISSUE THREAD

**Issue by mxmCherry** [valyala/fasthttp#51]
Hi,

Seems, that RequestCtx.SendFile does not consider Range header - it always sends the whole file (with Response.SendFile, which, obviously, contains no request headers).

But, for example, RequestCtx.SendFile analyzes If-Modified-Since.

It would be great, if RequestCtx.SendFile considered Range request header too, as FS does (I haven't tried it myself yet, but I looked through it's code + seen issue https://github.com/valyala/fasthttp/issues/47).

I understand, that implementing it would require some copy-pasting so Response.SendFile cannot be reused there, so it's also a design-related issue.

So, such behaviour is intentional (and I should stick to FS if I want Range analysis) or simply not implemented?

I've looked at master's code as of 83e17963591223c59f71b06d41cf4a4c8a2017d1 commit, if it matters :)

**Comment by valyala** [comment]
Consider using [ServeFile](https://godoc.org/github.com/valyala/fasthttp#ServeFile) instead. It sets `Content-Type`, supports byte ranges and transparent compression.
As for [RequestCtx.SendFile](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.SendFile), I tend to remove it in the future instead of trying to keep in sync two almost equivalent implementations in the code.

**Comment by mxmCherry** [comment]
Thanks, I'll probably give it a try (now using FS - works great).

**Comment by valyala** [comment]
Now `RequestCtx.SendFile` is an alias to `ServeFile` :)

**Comment by mxmCherry** [comment]
Excellent, thanks a lot :)
