### ISSUE TITLE
Benchmarks for comparison with net/http

### ISSUE THREAD

**Issue by janisz** [valyala/fasthttp#52]
Where are tests used to generate comparison in [README](https://github.com/valyala/fasthttp#http-server-performance-comparison-with-nethttp). [I can't find them](https://github.com/valyala/fasthttp/search?utf8=%E2%9C%93&q=NetHTTPServerGet+kServerGet&type=Code)

**Comment by valyala** [comment]
Code for server benchmarks is in [server_timing_test.go](https://github.com/valyala/fasthttp/blob/master/server_timing_test.go) .
Code for client benchmarks is in [client_timing_test.go](https://github.com/valyala/fasthttp/blob/master/client_timing_test.go) .

**Comment by janisz** [comment]
Thanks

**Comment by matrixik** [comment]
There are also new results in TechEmpower Framework Benchmarks https://www.techempower.com/benchmarks/

**Comment by valyala** [comment]
Cool! :) There are two minor downsides:
- TechEmpower Benchmarks were run on go 1.5, not on go 1.6, which is slightly faster than 1.5.
- fasthttp in prefork mode failed to run due to unknown reason. In this mode fasthttp starts a distinct server per CPU core using [SO_REUSEPORT](https://godoc.org/github.com/valyala/fasthttp/reuseport). This should result in perfect scalability on multi-CPU machines.
