### ISSUE TITLE
TimeoutHandler new goroutine for each request?

### ISSUE THREAD

**Issue by a-urth** [valyala/fasthttp#565]
I've noticed a lot of goroutines created while tracing our application, which uses fasthttp. And those were created here: https://github.com/valyala/fasthttp/blob/ed16dc07fd135b0c4bff506b7050f4555b3dd9c2/server.go#L393-L397

I understand why its like that, so my question is rather - doesn't it contradict idea of fasthttp processing requests in workers pool and making as less allocations as possible?

**Comment by erikdubbelboer** [comment]
We should indeed use a worker pool here as well.

I guess nobody using fasthttp for high qps workloads uses the `TimeoutHandler`. I know I don't cause I prefer to handle timeouts in my own code so I can abandon the work instead of just returning the response early but still continuing to do the processing.

**Comment by a-urth** [comment]
For us its the same, timeout was used... just because i guess. But I noticed that and was curious why its like that.
Anyway, thanks for the answer 👍

**Comment by ms2008** [comment]
Go1.11 has many optimizations for stack copy. After upgrading to Go1.1, is it necessary to use  goroutine pool any more?

Had been discussed here:

https://github.com/pingcap/tidb/pull/7564

**Comment by erikdubbelboer** [comment]
@ms2008 using a goroutine pool or not has nothing to do with this issue. But the question if we should abandon the worker pool we are using now in fasthttp is an interesting one. I wasn't aware of these optimizations. It's something I'm going to investigate in the near future when I have some time.

**Comment by erikdubbelboer** [comment]
I have done a lot of testing and having a goroutine pool is still slightly faster than just starting a new goroutine every time you need one.

Seeing as our code is currently stable with the pool I don't think we should remove it at this point. But maybe we should in the future to simplify our code.

Since the difference is really small I don't think we should complicate our code and implement a pool for `TimeoutHandler`. Especially if we might want to remove our goroutine pool in the future.

So I'm closing this issue for now.
