### ISSUE TITLE
tls can reload without restart the server but you do not support

### ISSUE THREAD

**Issue by 59duncom** [valyala/fasthttp#588]
tls can reload without restart the server but you do not support

in the (s *Server) AppendCert functions
after "s.tlsConfig.Certificates = append(s.tlsConfig.Certificates, cert)" this blank,
add "s.tlsConfig.BuildNameToCertificate()"
can reload without restart

**Comment by erikdubbelboer** [comment]
Reloading the certificate isn't as easy as just appending a certificate. You'll have to rebuild the tls listener as well.

The best way to currently do this is create a listener using
```go
ln, err := net.Listen("tcp", ":8080")
```

Then wrap it in a custom struct that ignores calls to `.Close()`. We do this because [`Server.Shutdown()`](https://godoc.org/github.com/valyala/fasthttp#Server.Shutdown) will call `.Close()` on the listener, but we don't want it to close.
```go
type IngoreCloseListener struct {
	ln net.Listener
}

func (icl *IngoreCloseListener) Accept() (net.Conn, error) {
	return icl.Accept()
}

func (icl *IngoreCloseListener) Close() error {
	// Ignore calls to Close.
	return nil
}

func (icl *IngoreCloseListener) Addr() net.Addr {
	return icl.Addr()
}
```

Then you create a `fasthttp.Server` object and use [`Server.ServeTLS()`](https://godoc.org/github.com/valyala/fasthttp#Server.ServeTLS) to listen for connections.

When you want to reload the certificate you just do the exact same thing again, creating a `fasthttp.Server` and calling [`Server.ServeTLS()`](https://godoc.org/github.com/valyala/fasthttp#Server.ServeTLS) on it with the same listener. And then you call [`Server.Shutdown()`](https://godoc.org/github.com/valyala/fasthttp#Server.Shutdown) on the old server object to stop that one.

I have never done this so I'm not 100% sure if it will work. But in theory it should when I look at the code.

**Comment by squidfunk** [comment]
@erikdubbelboer couldn't this be implemented in a simpler way by providing a custom implementation for [`tls.Config`'s `GetCertificate` function](https://stackoverflow.com/a/40883377)?

**Comment by erikdubbelboer** [comment]
@squidfunk I was not aware of that function. Yes that makes it much simpler. You just have to create your own `tls.Listener` which uses this `GetCertificate` function just like the linked post.
