### ISSUE TITLE
Question: can this library used in Google App Engine

### ISSUE THREAD

**Issue by kokizzu** [valyala/fasthttp#59]
link to Google App Engine link: https://cloud.google.com/appengine/docs/go/

**Comment by valyala** [comment]
It looks like fasthttp cannot be used in Google App Engine, since it doesn't provide the ability to accept incoming http connections, so fasthttp could intercept and process them with custom [net.Listener](https://golang.org/pkg/net/#Listener) passed to [Server.Serve](https://godoc.org/github.com/valyala/fasthttp#Server.Serve).

See http://stackoverflow.com/questions/10842915/how-to-build-an-tcp-listener-or-server-on-google-appengine-maybe-in-golang for more info.

Try filing a feature request for Google App Engine to add `net.Listener` for accepting incoming http connections.

**Comment by valyala** [comment]
I already filed the corresponding feature request in AppEngine - https://code.google.com/p/googleappengine/issues/detail?id=12771 .

**Comment by valyala** [comment]
Closing the issue. I hope AppEngine team will implement this feature soon :)
