### ISSUE TITLE
questions about dial

### ISSUE THREAD

**Issue by jamsonzan** [valyala/fasthttp#624]
hello ! somethings I don't understand
###  tcpdialer.go
```
go func() {
		var dr dialResult
		dr.conn, dr.err = net.DialTCP(network, nil, addr)
		ch <- dr
		if concurrencyCh != nil {
			<-concurrencyCh
		}
	}()
......
tc := AcquireTimer(timeout)
select {
	case dr := <-ch:
		conn = dr.conn
		err = dr.err
		dialResultChanPool.Put(ch)
	case <-tc.C:
		err = ErrDialTimeout
	}
......
```
why not use net.DialTimeout ?  for some feature ?

**Comment by erikdubbelboer** [comment]
I'm not sure why @valyala choose to implement his own timeout. I guess because it's a bit faster and generates less garbage as fasthttp uses a pool for the timer for example.

Maybe someone should do a test and see how well `net.DialTimeout` works here. If it is just as fast and generates the same amount of garbage it would be nice to clean up the code.

**Comment by jamsonzan** [comment]
now, I don't think this problem needs to be tangled!

**Comment by jamsonzan** [comment]
> now, I don't think this problem needs to be tangled!

we can see goroutine everywhere！
