### ISSUE TITLE
[Fileserver] Fileserver Memory Usage with 200k concurrent connections. 

### ISSUE THREAD

**Issue by siddharthg** [valyala/fasthttp#67]
Hi @valyala,

I am using the fileserver given in the example to serve files from a 4 core system on production. I load tested it on the server and could easily achieve 20k requests/second (this includes kafka produce of access logs). I have two queries, I would be really helpful if you can help me with the same. 

The issue I faced was when the number of concurrent connections went upto around 250k while serving a 300kb file to real users. At this moment the RAM (30GB) was full and the space on disk went to 0 starting from 80 GB and I had no other option apart from killing the processes. 

After going through the code, I am suspecting that request handler opens a file every time all the bigFileReaders are already in use, does this mean 200k concurrent connection created 200k bigFileReaders instances. Am I right on this? 

Does fileserver use sendfile for bigfiles?

**Comment by valyala** [comment]
Hi, @siddharthg 

> Does fileserver use sendfile for bigfiles?

Yes, it should use `sendfile` for files bigger than `maxSmallFileSize`, which is currently 8KB. But this depends on internals of Go standard library, so may break in the future Go releases. Currently it works as expected in go 1.5 and go 1.6.

> After going through the code, I am suspecting that request handler opens a file every time all the bigFileReaders are already in use, does this mean 200k concurrent connection created 200k bigFileReaders instances.

Yes. Fasthttp must open a file per each connection due to the current `sendfile` implementation in standard Go library. It cannot share the same file handler among distinct connections as `smallFileReader` does for files smaller than 8KB, since `sendfile` implementation in Go depends on the current file handler's position.

Try increasing `maxSmallFileSize` inside `fs.go` to the value exceeding file sizes you serve. This should significantly reduce the number of open files in the server process at the cost of higher CPU usage and, probably, slower transfer speeds.

**Comment by valyala** [comment]
You can also limit server's memory usage by setting [Server.Concurrency](https://godoc.org/github.com/valyala/fasthttp#Server) to the maximum allowed concurrent connections.

**Comment by valyala** [comment]
Just realised that `sendfile` implementation in go might have yet another problem - `sendfile` syscall requires a dedicated OS thread like any other syscall or `cgo` call do. This may result in a lot of OS threads when reading files from slow media (for instance, HDD or network storage), since `sendfile` under linux may block when reading data from the file even [in non-blocking mode](http://stackoverflow.com/a/11256656/274937). Nginx solves this problem by executing `sendfile` calls under linux on a dedicated thread pool with limited size - see [this article](https://www.nginx.com/blog/thread-pools-boost-performance-9x/) for details.

**Comment by siddharthg** [comment]
Thanks a lot for the reply. Most of the files I am serving lie between 100-400 KB.  But there are a lot of files, I am worried if I make the `maxSmallFileSize` to 400KB, how would the memory usage would be affecting. 

Also, after I switched on bytesRange, the number of Established connection starts gradually increasing. Which means either the collections are not closing, or they are waiting for the next request. 

Is there any way I can run the service on tcp4 instead of tcp6.

**Comment by valyala** [comment]
> I am worried if I make the maxSmallFileSize to 400KB, how would the memory usage would be affecting.

This shouldn't affect memory usage -  this just instructs `fasthttp` to avoid `sendfile` path for serving files smaller than 400KB. Though CPU usage may increase.

> Also, after I switched on bytesRange, the number of Established connection starts gradually increasing. Which means either the collections are not closing, or they are waiting for the next request.

By default `fasthttp` doesn't close incoming connections unless the client ask this either via using `HTTP/1.0` without `Connection: keep-alive' request header or via `Connection: close` request header. Such a behavior conforms [HTTP/1.1](https://en.wikipedia.org/wiki/HTTP_persistent_connection#HTTP_1.1).

`Fasthttp` server may be configured to close idle keep-alive connections after certain period of inactivity - see [Server.ReadTimeout](https://godoc.org/github.com/valyala/fasthttp#Server).

> Is there any way I can run the service on tcp4 instead of tcp6.

Yes. Just pass a custom listener to [Server.Serve](https://godoc.org/github.com/valyala/fasthttp#Server.Serve):

```go
        s := &fasthttp.Server{
            Handler: requestHandler,
            // Other Server params may be set up here.
        }

        // create tcp4-only listener
        ln, err := net.Listen("tcp4", ":8080")
        if err != nil {
                log.Fatalf("cannot listen tcp4: %s", err)
        }

        // start the server
        if err = s.Serve(ln); err != nil {
                log.Fatalf("error when serving: %s", err)
        }
```
