### ISSUE TITLE
How to disable Response after Hijacking ?

### ISSUE THREAD

**Issue by sintanial** [valyala/fasthttp#698]
I need send raw response in hijacked connection, how can i do this ?

**Comment by erikdubbelboer** [comment]
I'm afraid this is not possible at the moment.

I guess this could maybe be an additional boolean argument to [`RequestCtx.Hijack()`](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.Hijack). I might have time to implement this this weekend. Otherwise a pull request is always welcome of course.

**Comment by proyb6** [comment]
I'm curious to learn what is the use case for this?

**Comment by sintanial** [comment]
I use fasthttp only for fast parse request :). Then i need raw connection, and send raw response in this connection ;).
For example if i have proxy server, i need to get request, parse it, send to proxy resource and write raw response of this resource.
