### ISSUE TITLE
If we will use fasthttp for production purposes, these are my questions...

### ISSUE THREAD

**Issue by edwindvinas** [valyala/fasthttp#71]
Hi,

Kudos for creating this program which currently shows as the fastest on some tests! I just have some questions:
1) What would the lack of HTTP/2 support have any impact on our application? Our application is an API which receives requests from different systems.
2) When do we expect HTTP/2 and other upgrades to completed?
3) If we will use MongoDB instead of Postgresql, will we get the same high performance?

Again, I'm glad that your fasthttp is getting the fastest benchmark on some tests. I just really want to know from author's perspective if we can already use it production and what issues we may face due to some lacking features on it.

Thanks,
Edwin

**Comment by valyala** [comment]
> 1) What would the lack of HTTP/2 support have any impact on our application? Our application is an API which receives requests from different systems.

As I know, HTTP/2-compatible clients should be able to downgrade to HTTP/1.1 if the server doesn't support HTTP/2. So the lack of HTTP/2 support on the API server shouldn't break API clients, even if they support HTTP/2.

> 2) When do we expect HTTP/2 and other upgrades to completed?

There is no ETA for HTTP/2 support in fasthttp. Currently I have tasks with higher priority.

> 3) If we will use MongoDB instead of Postgresql, will we get the same high performance?

I don't know - just use it and [profile your app](http://blog.golang.org/profiling-go-programs). Prefer memory profiling over CPU profiling, since it usually gives better optimization opportunities. Use `go tool pprof --alloc_objects path/to/app path/to/mem.pprof` for spotting bottlenecks in your app.

**Comment by valyala** [comment]
Closing the issue, since all the questions are answered. Feel free creating new issues with additional questions.
