### ISSUE TITLE
fasthttputil.InmemoryListener requires fasthttp.Server.ReadTimeout

### ISSUE THREAD

**Issue by romshark** [valyala/fasthttp#745]
Using [fasthttp.Server.Shutdown](https://godoc.org/github.com/valyala/fasthttp#Server.Shutdown) in conjunction with [fasthttputil.InmemoryListener](https://godoc.org/github.com/valyala/fasthttp/fasthttputil#InmemoryListener) causes severe delays of up to 10 seconds: https://play.golang.org/p/s9uoL_JEweR by default. Setting `Server.ReadTimeout` to above `0` resolves the issue: https://play.golang.org/p/HbC5hlB7lbG

I wonder why an in-memory listener requires a read-timeout to be defined, I'd rather expect it to shut down immediately when `Server.Shutdown` is invoked.

**Comment by erikdubbelboer** [comment]
Using a normal listener will have the same problem. The documentation for `Shutdown` states:
```
Shutdown does not close keepalive connections so its recommended to set ReadTimeout
to something else than 0.
```

Internally the problem is that the server doesn't keep track of it's open connections, so it can't close them. Adding this would require some internal changes.

Maybe the documentation needs a bit bigger `WARNING` or something?
