### ISSUE TITLE
Shutdown is not working well！

### ISSUE THREAD

**Issue by GGXXLL** [valyala/fasthttp#769]
I'm learning golang. I finished this function by learning your code. It's from server_test.go > TestShutdown(). 
```golang
func run(server string, handler fasthttp.RequestHandler) {
	ln, err := net.Listen("tcp4", server)
	if err != nil {
		fmt.Println("create Listener error %v", err)
		panic(err)
	}
	s := &fasthttp.Server{
		Handler: handler,
	}
	serveCh := make(chan struct{})
	go func() {
		if err := s.Serve(ln); err != nil {
			fmt.Println("Server start error: %s", err)
			panic(err)
		}
		serveCh <- struct{}{}
	}()

	quit := make(chan os.Signal)
	signal.Notify(quit, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT)
	<-quit
	fmt.Println("Shutdown Server ...")

	shutdownCh := make(chan struct{})
	go func() {
		if err := s.Shutdown(); err != nil {
			fmt.Println("Shutdown error: %s", err)
		}
		shutdownCh <- struct{}{}
	}()
	done := 0
	for {
		select {
		case <-time.After(time.Second * 5):
			fmt.Println("Shutdown Server Timeout and Exited")
			return
		case <-serveCh:
			done++
		case <-shutdownCh:
			done++
		}

		if done >= 2 {
			fmt.Println("Server exited ...")
			return
		}
		time.Sleep(time.Millisecond * 100)
	}
}
```
I have some problems in using it. Then I tested on your test case and the same thing happened.

I use this command ```go test -run TestShutdown -v -count 1``` to run your test code.

It's normal when the sleep is 500. But, when the request ends before shutdown, the program cannot exit normally, such as changing sleep to 30，The result is ```shutdown took too long```.
```golang
	s := &Server{
		Handler: func(ctx *RequestCtx) {
			time.Sleep(time.Millisecond * 500)
			ctx.Success("aaa/bbb", []byte("real response"))
		},
	}
```
I try to find out where the problem is, and I discovered when I call shutdown after the request is finished, the value of  variable `open` in the `Shudown` function is always 1. 

I'm a new scholar, so I can't go further. I don't know what the problem is, or maybe it's my own fault. Please help me, thank you.

My English is not good. If there is any wrong grammar or words, please forgive me, thank you again.

**Comment by erikdubbelboer** [comment]
The problem is that the connection is kept alive even if your request has ended. You can either send a `Connection: close` header so keep-alive connections aren't used. You can set [`Server.DisableKeepalive`](https://godoc.org/github.com/valyala/fasthttp#Server.DisableKeepalive) or you can set [`Server.IdleTimeout`](https://godoc.org/github.com/valyala/fasthttp#Server.IdleTimeout) to something lower than the time you wait for the shutdown to complete.

You should also read the documentation of [`Server.Shutdown`](https://godoc.org/github.com/valyala/fasthttp#Server.Shutdown) which states that the function will only return after the shutdown is completed. So waiting for `serveCh` is not needed at all.
