### ISSUE TITLE
Request.CopyTo does not copy body when `multipart/form-data` 

### ISSUE THREAD

**Issue by Dot-H** [valyala/fasthttp#781]
Hi, while trying to pass-through a request, I tried to use the [`Request.CopyTo`](https://github.com/valyala/fasthttp/blob/db18810c877736b680b559f870349bf48e41aec5/http.go#L642) method.

This was working fine until one of the request had a `Content-Type` header set to `multipart/form-data` and a body. The destination request after `Request.CopyTo` was not receiving the body.

The only way I found to make it work was to set `DisablePreParseMultipartForm` to true in my `Server` structure.

Is it an expected behaviour ?

**Comment by erikdubbelboer** [comment]
I'm afraid that this is expected behavior. Unless you use `DisablePreParseMultipartForm` fasthttp will parse any multipart bodies automatically. The resulting [`multipart.Form`](https://golang.org/pkg/mime/multipart/#Form) can't easily be copied. Multi part form parsing also can't be turned off by default as current users might depend on this behavior. `DisablePreParseMultipartForm` is your best option here.
