### ISSUE TITLE
How it compares to net/http size wise ?

### ISSUE THREAD

**Issue by codemodify** [valyala/fasthttp#799]
net/http is known to have a lot of "fat" packaged into the final binary, this can be problematic for IoT devices, how does fasthttp perform from this perspective

**Comment by erikdubbelboer** [comment]
I have tested this and a binary with fasthttp is bigger than `net/http`. The reason is that fasthttp depends on the same standard libraries that `net/http` also depends on (like, `net` and `fmt`).

<details>
<summary>plain 1,200,912 bytes</summary>

    package main

    func main() {
    }
</details>

<details>
<summary><code>net/http</code> 6,825,204 bytes</summary>

    package main

    import _ "net/http"

    func main() {
    }
</details>

<details>
<summary>fasthttp 7,367,276 bytes</summary>

    package main

    import _ "github.com/valyala/fasthttp"

    func main() {
    }
</details>
