### ISSUE TITLE
[Bug/Question] Client disconnection notifier on server

### ISSUE THREAD

**Issue by gibix** [valyala/fasthttp#874]
I would like to be notified when the connection has been closed by the client on a long running event.

expected

```go
func GetBigFile(ctx *fasthttp.RequestCtx) {
	ctx.SendFile("/path")

	go func () {
		select {
		case <-ctx.Done():
			fmt.Println("The client has disconnected, do something")
		}
	}()
}
```

I wrote a small workaround with epool on the file descriptor to detect the closing event, but could be useful to have a convenient api for this.

**Comment by erikdubbelboer** [comment]
The problem is that fasthttp only starts sending the response when the handler returns. Anything you do with the RequestCtx after the handler has returned is undefined behavior (like your example).
I'm sorry but we don't have any plans to add an API for this as it doesn't seem many people need this and it wouldn't be very easy to add.
