### ISSUE TITLE
[Question] Testing: Redirect

### ISSUE THREAD

**Issue by hardcoar** [valyala/fasthttp#91]
Im trying to write a test to check whether the user sees the rendered page after being redirected once authenticated. I try to achieve this by reading the response body after authentication. 

i use fake requests using ReadWriter struct (from fasthttp test files) and somehow manage to code tests correctly but im stuck in checking if the user sees the rendirected page correctly.

- [x] **1.) is there any way i can check or catch the url where the user is redirected to?**

> Solved by: `resp.Header.Peek("Location")`

i use quicktemplate in rendering and check the rendered html just by reading the response body. however i just get ```""``` (an empty string) in response body after the user is redirected.

say, from POST request of ```/login``` url redirected to ```/someprofile```.

any of both should've rendered something but i got an empty string.

i checked the status code and it is correct. (302)
redirected means, the post request was successful.

- [ ] 
**2.)  is there any way i can read the response body where the user is redirected?**

> i still cant catch `resp.Body()` of where the user is redirected to....

forgive me im not that experienced yet.
thanks a lot!

**Comment by valyala** [comment]
@hardcoar , http responses with [status codes 3xx](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3) shouldn't contain body - you must follow the redirect in order to obtain response body, i.e. send yet another request to the url from `Location` response header. [Request.URI().Update](https://godoc.org/github.com/valyala/fasthttp#URI.Update) helper may be used for updating the url to navigate on redirect.

`Get*` and `Post` methods from [Client](https://godoc.org/github.com/valyala/fasthttp#Client) and [HostClient](https://godoc.org/github.com/valyala/fasthttp#HostClient) automatically follow redirects, while `Do*` methods don't follow redirects.

**Comment by hardcoar** [comment]
awesome. thanks!
