### ISSUE TITLE
How to access request protocol version information?

### ISSUE THREAD

**Issue by vishr** [valyala/fasthttp#92]
I have a need to find protocol version in the request, do you have methods/fields exposed for it?
From standard HTTP request:

``` go
Proto      string // "HTTP/1.0"
ProtoMajor int    // 1
ProtoMinor int    // 0
```

**Comment by valyala** [comment]
Currently there is only [RequestCtx.Request.Header.IsHTTP11](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.IsHTTP11) method exist, since initially fasthttp has been designed for HTTP/1.1 only. Incomplete HTTP/1.0 support has been added after that, so the method mentioned above has been appeared.

Support for other HTTP versions may be added to fasthttp later, so additional methods will appear for differentiating between distinct HTTP versions.

**Comment by vishr** [comment]
Got it.
