### ISSUE TITLE
How can I get protocol?

### ISSUE THREAD

**Issue by dbTBest** [valyala/fasthttp#928]
i only see RequestHeader.noHTTP11.How can i get protocol/majorVersion.minorVersion? i.e HTTP/1.0

**Comment by erikdubbelboer** [comment]
The only thing you can do is use [`RequestHeader.IsHTTP11()`](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.IsHTTP11) to check if it's HTTP/1.1. Otherwise you can assume it's HTTP/1.0. Fasthttp [doesn't keep the status line and only keeps the parsed state](https://github.com/valyala/fasthttp/blob/d0dfbd4494632e4bf398d1c0098e4c389a1c4356/header.go#L1711-L1729). It also only supports HTTP/1.0 or HTTP/1.1.
